# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
  labels:
    app: calculator
spec:
  replicas: 2 # Number of pod replicas
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: <your-dockerhub-username>/calculator:latest
        ports:
        - containerPort: 5000 # Change to the port your app listens on