# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator
  ports:
  - protocol: TCP
    port: 80          # The port exposed outside
    targetPort: 5000  # The port the container listens on
  type: LoadBalancer  # Exposes the app to the internet
